name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - none

env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node_modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          node_modules-

    - name: Install
      run: yarn --frozen-lockfile

    - name: Build
      run: yarn build

    - name: Release
      run: yarn release

    - name: Publish
      run: npm publish --access public